/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.management.system;

import java.awt.Color;
import java.awt.Font;
import static java.lang.Integer.parseInt;
import java.sql.ResultSet;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import project.InsertUpdateDelete;
import project.Select;

/**
 *
 * @author Admin
 */
public class AllUsers extends javax.swing.JFrame {

    /**
     * Creates new form AllUsers
     */
     static int room;
   
    public AllUsers() {
        initComponents();

        table.getTableHeader().setFont(new Font("Dialog", Font.BOLD, 14));
        JTableHeader tableHeader = table.getTableHeader();
        tableHeader.setForeground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manage = new javax.swing.JButton();
        checkIn = new javax.swing.JButton();
        checkOut = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        addroombtn = new javax.swing.JButton();
        listcheckoutBtn = new javax.swing.JButton();
        listcheckinBtn = new javax.swing.JButton();
        servicesbtn = new javax.swing.JButton();
        statisticsbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manage.setBackground(new java.awt.Color(255, 153, 153));
        manage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        manage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/room.png"))); // NOI18N
        manage.setText("List Of Room");
        manage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageMouseClicked(evt);
            }
        });
        getContentPane().add(manage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 320, 50));

        checkIn.setBackground(new java.awt.Color(255, 153, 153));
        checkIn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checkIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checkin.png"))); // NOI18N
        checkIn.setText("Check In");
        checkIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkInMouseClicked(evt);
            }
        });
        getContentPane().add(checkIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 320, 50));

        checkOut.setBackground(new java.awt.Color(255, 153, 153));
        checkOut.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        checkOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checkout.png"))); // NOI18N
        checkOut.setText("Check Out");
        checkOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkOutMouseClicked(evt);
            }
        });
        getContentPane().add(checkOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 320, 50));

        logout.setBackground(new java.awt.Color(0, 0, 153));
        logout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 140, 50));

        exit.setBackground(new java.awt.Color(255, 102, 102));
        exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        exit.setText("Exit");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, 110, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("WELCOME TO HOTEL BOOKING SYSTEM");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 760, 60));

        addroombtn.setBackground(new java.awt.Color(255, 153, 153));
        addroombtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addroombtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addroom.png"))); // NOI18N
        addroombtn.setText("Add Room");
        addroombtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addroombtnMouseClicked(evt);
            }
        });
        getContentPane().add(addroombtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 320, 50));

        listcheckoutBtn.setBackground(new java.awt.Color(255, 153, 153));
        listcheckoutBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        listcheckoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/customer.png"))); // NOI18N
        listcheckoutBtn.setText("List of Customer Check Out");
        listcheckoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listcheckoutBtnMouseClicked(evt);
            }
        });
        getContentPane().add(listcheckoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 320, 50));

        listcheckinBtn.setBackground(new java.awt.Color(255, 153, 153));
        listcheckinBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        listcheckinBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/customer.png"))); // NOI18N
        listcheckinBtn.setText("List of Customer Check In");
        listcheckinBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listcheckinBtnMouseClicked(evt);
            }
        });
        getContentPane().add(listcheckinBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 320, 50));

        servicesbtn.setBackground(new java.awt.Color(255, 153, 153));
        servicesbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        servicesbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/services.png"))); // NOI18N
        servicesbtn.setText("Services");
        servicesbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                servicesbtnMouseClicked(evt);
            }
        });
        getContentPane().add(servicesbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 320, 50));

        statisticsbtn.setBackground(new java.awt.Color(255, 153, 153));
        statisticsbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        statisticsbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stat_icon.png"))); // NOI18N
        statisticsbtn.setText("Statistics");
        statisticsbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statisticsbtnMouseClicked(evt);
            }
        });
        getContentPane().add(statisticsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 320, 50));
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, -1, -1));

        table.setBackground(new java.awt.Color(255, 153, 153));
        table.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room Number", "Room Type", "Bed", "Price", "Status"
            }
        ));
        table.setSelectionBackground(new java.awt.Color(255, 51, 102));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 770, 330));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("List of Rooms");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 180, 250, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 310, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hotelbg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 860, 490));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg.PNG"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        ResultSet rs = Select.getData("select * from room");
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        try {
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString("RoomNumber"), rs.getString("RoomType"), rs.getString("Bed"), rs.getString("Price"), rs.getString("Status")});
            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "You are not connected to database");
        }

    }//GEN-LAST:event_formComponentShown

 
    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked

        DefaultTableModel model = (DefaultTableModel) this.table.getModel();
        int index = table.getSelectedRow();
        JTable source = (JTable) evt.getSource();
        int row = source.rowAtPoint(evt.getPoint());
        int roomNumber = parseInt(table.getModel().getValueAt(row, 0).toString());
        room = roomNumber;
        
        JCheckBox update = new JCheckBox("UPDATE");
        JCheckBox delete = new JCheckBox("DELETE");
        Object[] options = {update, delete, "Yes"};
        int x = JOptionPane.showOptionDialog(null, " ",
                "SELECT AN OPTION!", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);

        System.out.println(index);
        try {
              
                    //Delete the data from database
                    if (delete.isSelected() && x != -1) {
                        String deleteString = "DELETE FROM room WHERE RoomNumber ='" + roomNumber + "'";
                        InsertUpdateDelete.setData(deleteString, "\"Deleted Successfully!\" ");
                        
                        int select = index;
                        if (select == index) {
                            model.removeRow(index);
                        } else {
                            JOptionPane.showMessageDialog(null, "Unable To Delete");
                        }


                    } else if (update.isSelected() && x != -1) {
                           
                           new UpdateRoom().setVisible(true);
                           this.setVisible(false);
                         
                    }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_tableMouseClicked

    private void manageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageMouseClicked
        // TODO add your handling code here:
                this.setVisible(false);
               new AllUsers().setVisible(true);
    }//GEN-LAST:event_manageMouseClicked

    private void addroombtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addroombtnMouseClicked
        // TODO add your handling code here:
          this.setVisible(false);
          new AddRoom().setVisible(true);
    }//GEN-LAST:event_addroombtnMouseClicked

    private void checkInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkInMouseClicked
        // TODO add your handling code here:
         this.setVisible(false);
          new CustomerCheckIn().setVisible(true);
    }//GEN-LAST:event_checkInMouseClicked

    private void checkOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkOutMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
          new CustomerCheckOut().setVisible(true);
    }//GEN-LAST:event_checkOutMouseClicked

    private void servicesbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_servicesbtnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Services().setVisible(true);
    }//GEN-LAST:event_servicesbtnMouseClicked

    private void statisticsbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statisticsbtnMouseClicked
        // TODO add your handling code here:
         this.setVisible(false);
          new Statistics().setVisible(true);
    }//GEN-LAST:event_statisticsbtnMouseClicked

    private void listcheckinBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listcheckinBtnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
          new ListCheckIn().setVisible(true);
    }//GEN-LAST:event_listcheckinBtnMouseClicked

    private void listcheckoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listcheckoutBtnMouseClicked
        // TODO add your handling code here:
         this.setVisible(false);
          new CustomersDetailsBills().setVisible(true);
    }//GEN-LAST:event_listcheckoutBtnMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
         int a = JOptionPane.showConfirmDialog(null, "Do you really want to logout?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_logoutMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
         int a = JOptionPane.showConfirmDialog(null, "Do you really want to close application?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addroombtn;
    private javax.swing.JButton checkIn;
    private javax.swing.JButton checkOut;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton listcheckinBtn;
    private javax.swing.JButton listcheckoutBtn;
    private javax.swing.JButton logout;
    private javax.swing.JButton manage;
    private javax.swing.JButton servicesbtn;
    private javax.swing.JButton statisticsbtn;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
