/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.management.system;

import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.omg.SendingContext.RunTime;
import project.*;
/**
 *
 * @author Admin
 */
public class CustomerCheckOut extends javax.swing.JFrame {

    /**
     * Creates new form CustomerCheckOut
     */
    public CustomerCheckOut() {
        initComponents();
        
        customerName.setEditable(false);
        checkinDate.setEditable(false);
        checkoutDate.setEditable(false);
        CustomerMobileNumber.setEditable(false);
        priceperDays.setEditable(false);
        numberOfdays.setEditable(false);
        TotalAmounttobepaid.setEditable(false);
        Email.setEditable(false);
        
    }
    
    int id =0;
    String Query;
    String roomType;
    String bed;
    String roomNo;
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RoomNUmber = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        customerName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        checkinDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        checkoutDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CustomerMobileNumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        priceperDays = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        numberOfdays = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TotalAmounttobepaid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        checkoutBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        RoomType = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Bed = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Engravers MT", 1, 24)); // NOI18N
        jLabel1.setText("Customer Check Out");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 0));
        jLabel2.setText("Room Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        RoomNUmber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RoomNUmber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomNUmberActionPerformed(evt);
            }
        });
        getContentPane().add(RoomNUmber, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 236, -1));

        searchBtn.setBackground(new java.awt.Color(204, 0, 0));
        searchBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Search");
        searchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBtnMouseClicked(evt);
            }
        });
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 0));
        jLabel3.setText("Customer Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        customerName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(customerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 236, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 0));
        jLabel4.setText("Check IN Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        checkinDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(checkinDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 237, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 0));
        jLabel5.setText("Check Out Date (Today)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, -1, -1));

        checkoutDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(checkoutDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 245, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 0));
        jLabel6.setText("Customer Mobile Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 170, -1, -1));

        CustomerMobileNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(CustomerMobileNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 190, 204, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 0));
        jLabel7.setText("Price Per Day");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 250, -1, -1));

        priceperDays.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(priceperDays, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 270, 190, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 0));
        jLabel8.setText("Number Of Days Stay");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, -1, -1));

        numberOfdays.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(numberOfdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 190, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 0));
        jLabel9.setText("Total Amount To Be Paid");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        TotalAmounttobepaid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(TotalAmounttobepaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 350, 140, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 0));
        jLabel10.setText("Email");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 20));

        Email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 200, -1));

        backBtn.setBackground(new java.awt.Color(255, 0, 0));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 440, -1, -1));

        checkoutBtn.setBackground(new java.awt.Color(0, 0, 204));
        checkoutBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        checkoutBtn.setText("Check Out");
        checkoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkoutBtnMouseClicked(evt);
            }
        });
        getContentPane().add(checkoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, -1, -1));

        CancelBtn.setBackground(new java.awt.Color(204, 0, 0));
        CancelBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        CancelBtn.setText("Cancel");
        CancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelBtnMouseClicked(evt);
            }
        });
        getContentPane().add(CancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Room Type");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        RoomType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(RoomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 160, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Bed");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, -1, 20));

        Bed.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(Bed, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 140, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checkIn.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RoomNUmberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomNUmberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomNUmberActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_searchBtnActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formComponentShown

    private void searchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseClicked
        // TODO add your handling code here:
         String roomNo =RoomNUmber.getText();
        boolean noroom = false ;
        try
        {
            ResultSet rs =Select.getData("select * from customer where RoomNumber='"+roomNo+"' and Checkout is NULL");
            if(rs.next())
            {
                noroom = true;
                RoomNUmber.setEditable(false);
                id=rs.getInt(1);
                customerName.setText(rs.getString(2));
                checkinDate.setText(rs.getString(10));
                CustomerMobileNumber.setText(rs.getString(3));
                priceperDays.setText(rs.getString(14));
                RoomType.setText(rs.getString(13));
                Bed.setText(rs.getString(12));
                
     
                SimpleDateFormat myFormat = new SimpleDateFormat("yyyy/MM/dd");
                Calendar cal =Calendar.getInstance();
                checkoutDate.setText(myFormat.format(cal.getTime()));
                String dateBeforeString=rs.getString(10);
                java.util.Date datebefore=myFormat.parse(dateBeforeString);
                String dateAfterStrig=myFormat.format(cal.getTime());
                java.util.Date dateAfter=myFormat.parse(dateAfterStrig);
                long difference=dateAfter.getTime() - datebefore.getTime();  
                int noOfDayStay=(int)(difference/(1000*60*60*24));
                if(noOfDayStay==0)
                {
                    
                    int numOfStay=Integer.parseInt(rs.getString(15));
                    numberOfdays.setText(rs.getString(15));
                    float price =Float.parseFloat(priceperDays.getText());
                    float total=price* numOfStay;
                    TotalAmounttobepaid.setText(Float.toString(total));
                    Email.setText(rs.getString(6));
                    roomType = rs.getString(13);
                    bed=rs.getString(12);
                    
                }
                   
                
            }else{
                 JOptionPane.showMessageDialog(null, "No booked room");

            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_searchBtnMouseClicked

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        // TODO add your handling code here:
           setVisible(false);
           new AllUsers().setVisible(true);
    }//GEN-LAST:event_backBtnMouseClicked

    private void CancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelBtnMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new CustomerCheckOut().setVisible(true);
    }//GEN-LAST:event_CancelBtnMouseClicked

    private void checkoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkoutBtnMouseClicked
        // TODO add your handling code here:
        String name =customerName.getText();
        String mobilenumber=CustomerMobileNumber.getText();
        String email =Email.getText();
        
        try
        {
            
        String checkout =checkoutDate.getText();
        String numberOfDaysStay = numberOfdays.getText();
        String totalAmount =TotalAmounttobepaid.getText();
        roomNo=RoomNUmber.getText();
        
        
        Query= "update customer set NumberOfDaysStay = '"+numberOfDaysStay+"', TotalAmount='"+totalAmount+"', CheckOut='"+checkout+"' where Id = '"+id+"'";
        InsertUpdateDelete.setData(Query, "");
        Query = "update room set Status ='Not Booked' where RoomNumber = '"+roomNo+"'";
        InsertUpdateDelete.setData(Query,"Customer Check Out Successfully!");
        
      
       
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
      
        this.setVisible(false);
        new CustomerCheckOut().setVisible(true);
        //call the function search button and displays the information
 
      
    }//GEN-LAST:event_checkoutBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerCheckOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bed;
    private javax.swing.JButton CancelBtn;
    private javax.swing.JTextField CustomerMobileNumber;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField RoomNUmber;
    private javax.swing.JTextField RoomType;
    private javax.swing.JTextField TotalAmounttobepaid;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField checkinDate;
    private javax.swing.JButton checkoutBtn;
    private javax.swing.JTextField checkoutDate;
    private javax.swing.JTextField customerName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField numberOfdays;
    private javax.swing.JTextField priceperDays;
    private javax.swing.JButton searchBtn;
    // End of variables declaration//GEN-END:variables
}
