/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.management.system;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.*;
import project.*;

/**
 *
 * @author Admin
 */
public class CustomerCheckIn extends javax.swing.JFrame {

    /**
     * Creates new form CustomerCheckIn
     */
    public CustomerCheckIn() {
        initComponents();
        datetxt.setEditable(false);
        PriceTxt.setEditable(false);
        SimpleDateFormat myFormat=new SimpleDateFormat("yyy/MM/dd");
        Calendar cal=Calendar.getInstance();
        datetxt.setText(myFormat.format(cal.getTime()));
    }
    String bed;
    String roomType;
    String roomNo;
    String jTextField8;
    
    public void roomDetails()
    {
        RoomNumber.removeAllItems();
        PriceTxt.setText("");
        bed=(String)Bed.getSelectedItem();
        roomType=(String)RoomType.getSelectedItem();
        try
        {
            ResultSet rs=Select.getData("select * from room where Bed='"+bed+"' and RoomType='"+roomType+"' and Status ='Not Booked'");
            while(rs.next())
            {
                RoomNumber.addItem(rs.getString(2));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        MobileNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Nationality = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        GenderField = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        idnumber = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Address = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        datetxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Bed = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        bookRoom = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        RoomNumber = new javax.swing.JComboBox<>();
        RoomType = new javax.swing.JComboBox<>();
        PriceTxt = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        IDType = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        numberofStay = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 118));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Engravers MT", 1, 24)); // NOI18N
        jLabel1.setText("Customer Check In");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 400, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 318, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Mobile Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        MobileNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(MobileNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 318, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Nationality");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        Nationality.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(Nationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 318, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Gender");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        GenderField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GenderField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(GenderField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 318, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("ID Number");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, 20));

        idnumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(idnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 303, -1));

        emailField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 318, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Address");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, -1, -1));

        Address.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 303, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Check In Date (Today)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, -1, -1));

        datetxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(datetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 303, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Bed");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, -1, -1));

        Bed.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Bed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple" }));
        Bed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BedActionPerformed(evt);
            }
        });
        getContentPane().add(Bed, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 281, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Room Type");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 230, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Room Number");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 300, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Price");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, -1, -1));

        bookRoom.setBackground(new java.awt.Color(0, 0, 204));
        bookRoom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bookRoom.setForeground(new java.awt.Color(255, 255, 255));
        bookRoom.setText("Book Room");
        bookRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookRoomActionPerformed(evt);
            }
        });
        getContentPane().add(bookRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 430, -1, -1));

        cancel.setBackground(new java.awt.Color(102, 0, 0));
        cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 430, -1, -1));

        RoomNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RoomNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomNumberActionPerformed(evt);
            }
        });
        getContentPane().add(RoomNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, 281, -1));

        RoomType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Air Condition", "Not Air Condition" }));
        RoomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomTypeActionPerformed(evt);
            }
        });
        getContentPane().add(RoomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, 281, -1));

        PriceTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(PriceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 380, 280, -1));

        backBtn.setBackground(new java.awt.Color(204, 0, 0));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 480, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("ID Type");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        IDType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IDType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTypeActionPerformed(evt);
            }
        });
        getContentPane().add(IDType, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 300, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Number of Days Stay");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        numberofStay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numberofStay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberofStayActionPerformed(evt);
            }
        });
        getContentPane().add(numberofStay, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 300, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checkIn.jpg"))); // NOI18N
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AllUsers().setVisible(true);
        
    }//GEN-LAST:event_backBtnActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        
        setVisible(false);
        new CustomerCheckIn().setVisible(true);
    }//GEN-LAST:event_cancelActionPerformed

    private void RoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomTypeActionPerformed
        // TODO add your handling code here:
        roomDetails();
        
    }//GEN-LAST:event_RoomTypeActionPerformed

    private void RoomNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomNumberActionPerformed
        // TODO add your handling code here:
       roomNo = (String)RoomNumber.getSelectedItem();
        try
        {
            ResultSet rs =Select.getData("select * from room  where RoomNumber='"+roomNo+"'");
            while(rs.next())
            {
                PriceTxt.setText(rs.getString(5));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_RoomNumberActionPerformed

    private void BedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BedActionPerformed
        // TODO add your handling code here:
         roomDetails();
    }//GEN-LAST:event_BedActionPerformed

    private void bookRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookRoomActionPerformed
        // TODO add your handling code here:
//        int id=1;
        String name=this.name.getText();
        String mobileNumber=MobileNumber.getText();
        String nationality=Nationality.getText();
        String gender=(String)GenderField.getSelectedItem();
        String email=emailField.getText();
        String idType =IDType.getText();
        String idProof=idnumber.getText();
        String noDays =numberofStay.getText();
        String address=Address.getText();
        String checkIN=datetxt.getText();
        String bed=(String)Bed.getSelectedItem();
        String roomType=(String)RoomType.getSelectedItem();
        String roomNo=(String)RoomNumber.getSelectedItem();
        String price =PriceTxt.getText();
        String Query = "select max(Id) from customer";  
        
        try
        {
            Integer.parseInt(mobileNumber); 
            Integer.parseInt(idProof); 
            
            try
            {
            ResultSet rs =Select.getData(Query);
            while(rs.next())
            {

               if(!price.equals(""))
               {
                   String Queryupdatebook="update room set Status='Booked' where RoomNumber='"+roomNo+"'";
                   InsertUpdateDelete.setData(Queryupdatebook, "");
                    Query="INSERT INTO customer(Name,MobileNumber,Nationality,Gender,Email,IdType,IdNumber,NumberOfDaysStay,Address,CheckIn,RoomNumber,Bed,roomType,pricePerDay) "
                           + "" + "VALUES ('"+name+"','"+mobileNumber+"','"+nationality+"','"+gender+"','"+email+"','"+idType+"','"+idProof+"','"+noDays+"','"+address+"','"+checkIN+"','"+roomNo+"','"+bed+"','"+roomType+"','"+price+"')";
       
                   InsertUpdateDelete.setData(Query,"Customer Check In Successfully!");
                   setVisible(false);
                   new CustomerCheckIn().setVisible(true);
               }
            }   
            }catch(SQLException e)
            {
                 JOptionPane.showMessageDialog(null, "Failed to connect to database");
            }    
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "You entered an invalid value! Please try again.");
        }
        
        
        
        
    }//GEN-LAST:event_bookRoomActionPerformed

    private void IDTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTypeActionPerformed

    private void numberofStayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberofStayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberofStayActionPerformed

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerCheckIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JComboBox<String> Bed;
    private javax.swing.JComboBox<String> GenderField;
    private javax.swing.JTextField IDType;
    private javax.swing.JTextField MobileNumber;
    private javax.swing.JTextField Nationality;
    private javax.swing.JTextField PriceTxt;
    private javax.swing.JComboBox<String> RoomNumber;
    private javax.swing.JComboBox<String> RoomType;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton bookRoom;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField datetxt;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField idnumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField name;
    private javax.swing.JTextField numberofStay;
    // End of variables declaration//GEN-END:variables

    private String myFormat(Date time) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
