/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.management.system;

import java.awt.Color;
import java.awt.Font;
import static java.lang.Integer.parseInt;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import project.InsertUpdateDelete;
import project.Select;
/**
 *
 * @author Admin
 */
public class Services extends javax.swing.JFrame {

    /**
     * Creates new form Services
     */
    public Services() {
        initComponents();
        
      table.getTableHeader().setFont( new Font( "Dialog" , Font.BOLD, 14 ));
      JTableHeader tableHeader = table.getTableHeader();
      tableHeader.setForeground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        food = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        FoodPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        DrinkName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Price = new javax.swing.JTextField();
        Pay = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        totalAmount = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Services");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setText("Food");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Food Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        food.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        food.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodActionPerformed(evt);
            }
        });
        getContentPane().add(food, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 200, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Price");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        FoodPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FoodPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FoodPriceActionPerformed(evt);
            }
        });
        getContentPane().add(FoodPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 200, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Drink Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        DrinkName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(DrinkName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 200, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Price");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        Price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 200, -1));

        Pay.setBackground(new java.awt.Color(0, 0, 255));
        Pay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Pay.setForeground(new java.awt.Color(255, 255, 255));
        Pay.setText("Pay");
        Pay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PayMouseClicked(evt);
            }
        });
        Pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayActionPerformed(evt);
            }
        });
        getContentPane().add(Pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));

        cancel.setBackground(new java.awt.Color(255, 0, 0));
        cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));

        table.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food ID", "Food Name", "Price", "Drink Name", "Price", "Total"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 650, 235));

        backBtn.setBackground(new java.awt.Color(204, 0, 0));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 410, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Total ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        totalAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(totalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 200, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/foodB.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FoodPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FoodPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FoodPriceActionPerformed

    
            
    private void PayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayActionPerformed
        String foodName = food.getText();
        String foodPrice = FoodPrice.getText();
        String drinkName = DrinkName.getText();
        String drinkPrice = Price.getText();
        String total = totalAmount.getText();
        
  
        try
        {
            Integer.parseInt(foodPrice); 
            Integer.parseInt(drinkPrice); 
             
             int fprice =Integer.parseInt(FoodPrice.getText());
             int dprice =Integer.parseInt(Price.getText());
             double totalPrice= fprice + dprice;
            
             try
             {
                  totalAmount.setText(Double.toString(totalPrice));
                  JOptionPane.showMessageDialog(null, " The total amount is '"+totalAmount.getText()+"' " );
           
              try
            {
                  String query = "Insert into food(foodName,foodPrice,drinkName,drinkPrice,total)"+" values ('"+foodName+"','"+foodPrice+"','"+drinkName+"','"+drinkPrice+"','"+totalAmount+"')";
                  InsertUpdateDelete.setData(query,""); 
            }catch(Exception e)
            {
                 JOptionPane.showMessageDialog(null, "Failed to insert!");
            }
             
             }catch(Exception e)
             {
                 JOptionPane.showMessageDialog(null, "Error!");
             }
           
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Invalid input!");
        }
             
       setVisible(false);
       new Services().setVisible(true);
    }//GEN-LAST:event_PayActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        setVisible(false);
        new AllUsers().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        ResultSet rs=Select.getData("select * from food");
        DefaultTableModel model =(DefaultTableModel)table.getModel();
        
        try
        {
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString("foodId"),rs.getString("foodName"),rs.getString("foodPrice"),rs.getString("drinkName"),rs.getString("drinkPrice"),rs.getString("total")});              
            }
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_formComponentShown

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
       setVisible(false);
        new Services().setVisible(true);
    }//GEN-LAST:event_cancelActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        DefaultTableModel model = (DefaultTableModel) this.table.getModel();
        int index =table.getSelectedRow();
        JTable source = (JTable) evt.getSource();
        int row = source.rowAtPoint(evt.getPoint());
        int id = parseInt(table.getModel().getValueAt(row, 0).toString());
        
       try
        {
              int select = index; 
              if (select == index){
              model.removeRow(index);
              int question = JOptionPane.showConfirmDialog(null, "Do really want to delete this data?","Select",JOptionPane.YES_NO_OPTION);
              try
              {
                  //Delete the data from database
                  if(question == 0)
                  {
                      String deleteString = "DELETE FROM food WHERE foodId ='"+id+"'";
                      InsertUpdateDelete.setData(deleteString,"\"Deleted Successfully!\" ");
                      
                  }else
                  {
                      new Services().setVisible(true);
                  }
                          
              }catch(Exception e)
              {
                   JOptionPane.showMessageDialog(null, e);
              }
             
            }else {
              JOptionPane.showMessageDialog(null, "Unable To Delete");
        }
           
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tableMouseClicked

    private void foodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodActionPerformed

    private void PayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PayMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_PayMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Services().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DrinkName;
    private javax.swing.JTextField FoodPrice;
    private javax.swing.JButton Pay;
    private javax.swing.JTextField Price;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField food;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField totalAmount;
    // End of variables declaration//GEN-END:variables
}
